name: Sync Widgets
on:
  schedule:
    - cron: '0 3 * * *' 
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requests
        run: pip install requests
      - name: Sync widgets
        run: python .github/scripts/sync_widgets.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add ForwardWidgets.fwd
          git diff --cached --quiet || git commit -m '自动同步 widgets 版本信息'
          git push
      - name: Telegram Notification
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage" \
            -d chat_id=${TG_CHAT_ID} \
            -d text="ForwardWidgets.fwd 已自动同步并提交。"